server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/user_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: AUTH-SERVER


secure-key: ${SECURE_KEY_STR:8Xc5HXT4fRYeGL5uLyNgaGg4vtMldmLhjtIvD2gLoK4=}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://eureka-0.eureka.default.svc.cluster.local:8761/eureka"



